services:
  books-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # Mounts volumes from the host machine to the container.
      - .:/app  # Maps the current directory on the host to /app directory in the container.
    container_name: books-api-service
    restart: always
    command: ./start_books_api.sh --environment=local
    ports:
      - "${HOST_MACHINE_WEB_PORT:-8001}:8001"  # Map port from host machine or default to 8000
    env_file:
      - ./.env
      - ./.env.secrets
    networks:
      - books_api_network

  books-api-celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-api-celery
    restart: always
    command: celery -A books_api_service worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
      - ./.env.secrets
    depends_on:
      - books-api-service
    networks:
      - books_api_network

networks:
  books_api_network:
    external: true