version: '3.8'

services:
  books-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # Mounts volumes from the host machine to the container.
      - .:/app  # Maps the current directory on the host to /app directory in the container.
    container_name: books-api-service
    restart: always
    command: ./start_books_api.sh --environment=local
    ports:
      - "${HOST_MACHINE_WEB_PORT:-8000}:8000"  # Map port from host machine or default to 8000
    env_file:
      - ./.env
      - ./.env.secrets
    networks:
      - books_api_network

networks:
  books_api_network:
    external: true